//
//  LinkedInProfileFields.h
//  SocialEngine
//
//  Created by Maxim Letushov on 9/22/12.
//
//

#ifndef SocialEngine_LinkedInProfileFields_h
#define SocialEngine_LinkedInProfileFields_h

static const long LINKEDIN_PROFILE_FIELD__ID = 1;
static const long LINKEDIN_PROFILE_FIELD__FIRST_NAME = 2;
static const long LINKEDIN_PROFILE_FIELD__LAST_NAME = 4;
static const long LINKEDIN_PROFILE_FIELD__HEADLINE = 8;
static const long LINKEDIN_PROFILE_FIELD__LOCATION = 16;
// 32 reserved
static const long LINKEDIN_PROFILE_FIELD__INDUSTRY = 64;
static const long LINKEDIN_PROFILE_FIELD__CURRENT_SHARE = 128;
static const long LINKEDIN_PROFILE_FIELD__NUM_CONNECTIONS = 256;
static const long LINKEDIN_PROFILE_FIELD__SUMMARY = 512;
static const long LINKEDIN_PROFILE_FIELD__POSITIONS = 1024;
static const long LINKEDIN_PROFILE_FIELD__PICTURE_URL = 2048;
static const long LINKEDIN_PROFILE_FIELD__EMAIL_ADDRESS = 4096;
static const long LINKEDIN_PROFILE_FIELD__EDUCATIONS = 8192;
static const long LINKEDIN_PROFILE_FIELD__LAST_MODIFIED_TIMESTAMP = 16384;

static const long LINKEDIN_PROFILE_FIELDS__ALL =
LINKEDIN_PROFILE_FIELD__ID |
LINKEDIN_PROFILE_FIELD__FIRST_NAME |
LINKEDIN_PROFILE_FIELD__LAST_NAME |
LINKEDIN_PROFILE_FIELD__HEADLINE |
LINKEDIN_PROFILE_FIELD__LOCATION |
LINKEDIN_PROFILE_FIELD__INDUSTRY |
LINKEDIN_PROFILE_FIELD__CURRENT_SHARE |
LINKEDIN_PROFILE_FIELD__NUM_CONNECTIONS |
LINKEDIN_PROFILE_FIELD__SUMMARY |
LINKEDIN_PROFILE_FIELD__POSITIONS |
LINKEDIN_PROFILE_FIELD__PICTURE_URL |
LINKEDIN_PROFILE_FIELD__EMAIL_ADDRESS |
LINKEDIN_PROFILE_FIELD__EDUCATIONS |
LINKEDIN_PROFILE_FIELD__LAST_MODIFIED_TIMESTAMP;

#endif
